Algoritmo "semnome"
// 
//  
// EXERCICIO 6
Var
valorInicial: real
deposito: real
saldoAtual: real


// Exercicio 07
Inicio
escreval("Digite o valor que quer iniciar na conta")
leia(valorInicial)
escreval("Digite o valor quer depositar ")
leia(deposito)
saldoAtual <- deposito + valorInicial
escreval(" Seu valor inicial foi ",valorInicial , "Seu deposito foi de ", deposito, "seu saldo atual é de ", saldoAtual)




Fimalgoritmo