Algoritmo "semnome"
// 
//  
// EXERCICIO 6
Var
nome: caractere
idade: inteiro



Inicio

escreva("Digite sua idade ")
leia (idade)
SE (idade > 18)ENTAO
escreva("verdadeiro")
fimse
SE (idade <> 25)ENTAO
escreva("FALSO")
fimse
SE (idade <> 25) E (nome = "MARCOS")ENTAO
escreva("Falso")
fimse
SE (idade <> 25) OU (nome = "MARCOS")ENTAO
escreva("Verdadeiro")
fimse
SE ((idade mod 2) = 0)ENTAO
escreva("Verdadeiro")
fimse




Fimalgoritmo